# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jade Systems Inc.
email: info@jadesystems.ca
description: >- # this means to ignore newlines until "baseurl:"
  Jade Systems builds custom web applications for enterprises and start-ups.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lenchoreyes
github_username:  lcreid

# Paginator for blog posts.
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules

collections:
  knowledgebase:
    output: true

exclude:
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - Vagrantfile
  - yarn.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Procfile*
  - log/
  - lib/
  - node_modules/
  - .devcontainer/
  - .vscode/
  - .vscode-server/
  - compose.yml
  - compose-override.yml
  - .cache/
  - .npm/
  - .dotnet/
  - .bash_history

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

